---
- hosts: 172.31.8.172 
  becomes: yes  
  tasks: 
  - name: i want to install direct linux command 
    command: hostname -f 
    register: myfirsttaskresult 


    
  - name: i want to display first task result 
    debug:
     msg:"{{myfirsttaskresult}}" 