---
- hosts: 
  become: yes
  tasks: 
  - name: install git 
    apt: 
       name: git 
       state: present
  - name: tree
    apt: 
       name: tree 
       state: present 
  - ignore erros: yes 
  - name: wget 
    apt: 
      name: wget 
      state: present 
                