---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserber on ubuntu nodes
    apt:
      name: apache2
      state: present 
  - name: i want to install wget on ubuntu nodes
    apt:
      name: wget
      state: present   
  - name: i want to install tree
    apt:
     name: tree
     state: present 