---
- hosts: mywebservers
  become: yes 
  tasks: 
  - name: install java on ubuntu
    apt: 
     name: "{{jituonubuntu}}"
     state: present 
    when: ansible_os_family =="Debian"  
  - name: install java on redhat 
    ansible.builtin.dnf:
     name: "{{ashishonredhat}}"
     state: present
    when: ansible_os_family =="RedHat"     