---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu nodes
    apt:
     name: apache2
     state: presents  

  - name: i want to install wgetname
    apt:
     name: wget
     state: present 

  - name: i want to start apache2 on ubuntu nodes
    service:
     name: apache2
     state: started 

  - name: i want to ping all nodes
    ping:      