---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu nodes
    apt:
     name: apache2
     state: present

  - name: i want to install nginx
    apt:
     name: nginx
     state: present 

  - name: i want to start apache2 on ubuntu nodes
    service:
     name: apache2
     state: started 

  - name: i want to start nginx on ubuntu nodes
    service:
     name: nginx
     state: started       