--- 
- hosts: all
  become: yes    
  tasks: 
  - name: i want to ping all nodes
    ping: 
  - name: i want to install websrever on ubuntu ansible nodes 
    apt: 
      name: apache2
      state: absent 
  - name: i want to install tree on ubuntu ansible nodes 
    apt: 
      name: tree 
      state: absent      
  - name: i want to install wget on ubuntu ansible nodes 
    apt:
      name: wget 
      state: present

        