--- 
hosts: mywebservers 
become: yes 
tasks: 
- name: i wnt to install webserver on ubuntu nodes
  apt: 
    name: apache2
    state: present 

- name: i want to install webserver on redhat nodes
  ansible.builtin.dnf:
     name: httpd
     state: present