--- 
- hosts: mywebservers 
  become: yes 
  tasks: 
  - name: i wnt to install webserver on ubuntu nodes
    apt: 
     name: "{{jitu}}"
     state: present
    when: ansible_os_family =="Debian"   

  - name: i want to install webserver on redhat nodes
    ansible.builtin.dnf:
     name: "{{ashish}}"
     state: present
    when: ansible_os_family =="RedHat" 

# "RedHat"="Debian"      
