--- 
- hosts: 172.31.8.172
  become: yes 
  gather_facts: true
  tasks: 
  - name: i want to install webserver on ubuntu nodes 
    apt: 
      name: apache2 
      state: present 
    when: ansible_os_family == "debian"
  - name: i want to start webserver on ubuntu nodes 
    service:     
  -   name: i want to start webserver on ubuntu nodes
      service:
       name: apache2
       state: started 
            